### ISSUE TITLE
App thinning/bitcode problem when uploading to iTunesConnect

### ISSUE THREAD

**Issue by ronnie70** [DeclarativeHub/Bond#529]
When trying to upload my app to iTunesConnect, with the option "Include bitcode for iOS content" enabled, I get the following error:
`ipatool failed with an exception: #<CmdSpec::NonZeroExcitException: /Applications/Xcode.app/Contents/Developer/usr/bin/bitcode-build-tool exited with pid 69243 exit 1
Stdout:
    Debug: SDK path: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk
    Debug: PATH: ['/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin', '/Applications/Xcode.app/Contents/Developer/usr/bin']
    Debug: Using: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo
    MachoInfo: cd /
    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo" "-info" "/var/folders/k1/s407rnvx4hd751d3n_yvh5080000gn/T/ipatool20180504-67815-7zaf75/thinned/armv7/Payload/autoSense.app/Frameworks/Bond.framework/Bond"`

Is this a known issue with the Bond framework?

**Comment by srdanrasic** [comment]
Hi @ronnie70,

No, this is first time I see something like that. I can't think of anything specific to Bond that would cause this. How are you integrating Bond? CocoaPods or Carthage. I'd check is everything properly configured and linked. Also check signing options.

**Comment by ronnie70** [comment]
Hi,

I did some further investigation and it definitely seems to point to a problem in the Bond.framework.

What I did was making a fresh empty project and (using Carthage) adding different frameworks to the project (and making sure the "/usr/local/bin/carthage copy-frameworks" was called for this particular framework). Then I archive the project and do an Ad Hoc export.

This works fine for all frameworks (Differ, Realm, Moya, SwiftyBeaver, Result), but only with the Bond.framework the above mentioned error message is shown.

**Comment by ronnie70** [comment]
@sebskuse, 
Might be, this is what it says at the bottom of the alert:
`error: Ld: cd /var/folders/k1/s407rnvx4hd751d3n_yvh5080000gn/T/tempYnGgru
    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" "-arch" "arm64" "-dylib" "-compatibility_version" "1.0.0" "-current_version" "1.0.0.0.0" "-install_name" "@rpath/Bond.framework/Bond" "-ios_version_min" "8.0.0" "-rpath" "@executable_path/Frameworks" "-rpath" "@loader_path/Frameworks" "-dead_strip" "-application_extension" "-syslibroot" "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk" "-sdk_version" "11.3.0" "-filelist" "/private/var/folders/k1/s407rnvx4hd751d3n_yvh5080000gn/T/BondRuglIx/Bond.arm64.out.LinkFileList" "-ignore_auto_link" "-allow_dead_duplicates" "/var/folders/k1/s407rnvx4hd751d3n_yvh5080000gn/T/ipatool20180508-66491-3f8ejc/thinned/arm64/Payload/appThingTest.app/Frameworks/Differ.framework/Differ" "/var/folders/k1/s407rnvx4hd751d3n_yvh5080000gn/T/ipatool20180508-66491-3f8ejc/thinned/arm64/Payload/appThingTest.app/Frameworks/ReactiveKit.framework/ReactiveKit" "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk/System/Library/Frameworks/Foundation.framework/Foundation.tbd" "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk/usr/lib/libobjc.A.tbd" "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk/usr/lib/libSystem.B.tbd" "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation.tbd" "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk/System/Library/Frameworks/QuartzCore.framework/QuartzCore.tbd" "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk/System/Library/Frameworks/UIKit.framework/UIKit.tbd" "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk/usr/lib/libobjc.A.tbd" "/var/folders/k1/s407rnvx4hd751d3n_yvh5080000gn/T/ipatool20180508-66491-3f8ejc/thinned/arm64/Payload/appThingTest.app/Frameworks/libswiftCore.dylib" "/var/folders/k1/s407rnvx4hd751d3n_yvh5080000gn/T/ipatool20180508-66491-3f8ejc/thinned/arm64/Payload/appThingTest.app/Frameworks/libswiftCoreFoundation.dylib" "/var/folders/k1/s407rnvx4hd751d3n_yvh5080000gn/T/ipatool20180508-66491-3f8ejc/thinned/arm64/Payload/appThingTest.app/Frameworks/libswiftCoreGraphics.dylib" "/var/folders/k1/s407rnvx4hd751d3n_yvh5080000gn/T/ipatool20180508-66491-3f8ejc/thinned/arm64/Payload/appThingTest.app/Frameworks/libswiftCoreImage.dylib" "/var/folders/k1/s407rnvx4hd751d3n_yvh5080000gn/T/ipatool20180508-66491-3f8ejc/thinned/arm64/Payload/appThingTest.app/Frameworks/libswiftDarwin.dylib" "/var/folders/k1/s407rnvx4hd751d3n_yvh5080000gn/T/ipatool20180508-66491-3f8ejc/thinned/arm64/Payload/appThingTest.app/Frameworks/libswiftDispatch.dylib" "/var/folders/k1/s407rnvx4hd751d3n_yvh5080000gn/T/ipatool20180508-66491-3f8ejc/thinned/arm64/Payload/appThingTest.app/Frameworks/libswiftFoundation.dylib" "/var/folders/k1/s407rnvx4hd751d3n_yvh5080000gn/T/ipatool20180508-66491-3f8ejc/thinned/arm64/Payload/appThingTest.app/Frameworks/libswiftMetal.dylib" "/var/folders/k1/s407rnvx4hd751d3n_yvh5080000gn/T/ipatool20180508-66491-3f8ejc/thinned/arm64/Payload/appThingTest.app/Frameworks/libswiftObjectiveC.dylib" "/var/folders/k1/s407rnvx4hd751d3n_yvh5080000gn/T/ipatool20180508-66491-3f8ejc/thinned/arm64/Payload/appThingTest.app/Frameworks/libswiftQuartzCore.dylib" "/var/folders/k1/s407rnvx4hd751d3n_yvh5080000gn/T/ipatool20180508-66491-3f8ejc/thinned/arm64/Payload/appThingTest.app/Frameworks/libswiftUIKit.dylib" "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/lib/darwin/libclang_rt.ios.a" "-o" "/private/var/folders/k1/s407rnvx4hd751d3n_yvh5080000gn/T/BondRuglIx/Bond.arm64.out" 
    -= Output =-
    Undefined symbols for architecture arm64:
      "__T06Differ12ExtendedDiffV5patchSayAA0B5PatchOy7ElementQzGGx4from_x2toSbAcGO_AMtcSg4sortts10CollectionRzs9EquatableAHRQlF", referenced from:
          __hidden#1268_ in 14.o
          __hidden#3563_ in 52.o
    ld: symbol(s) not found for architecture arm64
    Exited with 1
    
    
    error: Failed to compile bundle: /var/folders/k1/s407rnvx4hd751d3n_yvh5080000gn/T/BondRuglIx/Bond.arm64.xar`

**Comment by sebskuse** [comment]
Yeah, that's the same log I was getting. 

Have you tried a rebuild using Carthage? It should pull 1.2.3 in, which should resolve the issue.

**Comment by ronnie70** [comment]
Hmmm I just tried and I see it pulled in Differ 1.2.3, but when doing an AdHoc export I still get the sam error unfortunately...

**Comment by ronnie70** [comment]
BTW, disabling code coverage in Release build also doesn't seem to fix it...

**Comment by sebskuse** [comment]
Hm, yeah I'm still getting a failure when exporting for App Thinning after rebuilding Bond using Carthage. 

Looking at `Carthage/Checkouts/Bond/Carthage/Checkouts`, the version of Differ it's got has code coverage still switched on, so it looks like it's still pulling the old version. Last week we ended up rebuilding Bond manually outside of Carthage with codecov switched off for Release which seemed to resolve the issue as a quick fix to get something in the store.

**Comment by srdanrasic** [comment]
Hi @ronnie70 @sebskuse I've just released 6.8.3 with code coverage disabled in release configuration. I've also released ReactiveKit 9.3.5 with code coverage disabled in release configuration.

Let me know if this helps.

**Comment by sebskuse** [comment]
Thanks @srdanrasic, looks like this is working for me :+1:

**Comment by ronnie70** [comment]
Thanks @srdanrasic and @sebskuse, it's working!
